from src.explaining.cam.GradCam import GradCAM
from src.explaining.explain_utils import run_model


def run_gradcam(
    model,
    input_tensor,
    target_layer,
    class_idx=None,
    ):
    '''
    Runs a forward pass and computes Grad-CAM for a given model layer.
    This function operates purely on model and tensor level.
    Assumes input_tensor has batch size 1 and gradients are enabled.
    Returns:
    - Heatmap generated by the GradCam class
    - Raw logits (unnormalized class scores)
    '''

    # Register hooks on the target layer
    grad_cam = GradCAM(target_layer)

    # Evaluate model + Forward pass
    logits, _ = run_model(model, input_tensor, require_grad=True)

    # Default: explain predicted class
    if class_idx is None:
        class_idx = logits.argmax(dim=1).item()

    model.zero_grad()

    # Backward pass + CAM computation
    cam = grad_cam.generate(logits, class_idx)

    # Remove used forward and backward hooks
    grad_cam.remove()

    return cam, logits.detach().cpu()