from explaining.cam.GradCam import GradCAM


def run_gradcam(
    model,
    input_tensor,
    target_layer,
    class_idx=None,
    ):
    '''
    Runs a foward pass and computes Grad-CAM for a given model layer.
    This function operates purely on model and tensor level.
    Returns:
    - Heatmap generated by the GradCam class
    - Class probabilities
    '''

    # Evaluate model
    model.eval()

    # Register hooks on the target layer
    grad_cam = GradCAM(target_layer)

    # Forward pass
    logits = model(input_tensor)

    # Default: explain predicted class
    if class_idx is None:
        class_idx = logits.argmax(dim=1).item()

    # Backward pass + CAM omputation
    cam = grad_cam.generate(logits, class_idx)

    # Remove used forward and backward hooks
    grad_cam.remove()

    return cam, logits
